services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1", "-u${DATABASE_MYSQLUSER}", "-p${DATABASE_MYSQLPASSWORD}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s