services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./internal/db/mysql_data:/var/lib/mysql
      - ./internal/db/mysql_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$DATABASE_MYSQL_USER -p$$DATABASE_MYSQL_PASSWORD
      interval: 1s
      retries: 100
